apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - name: web
              containerPort: 9093
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            # Le secret SMTP, monté comme fichier (lecture seule)
            - name: smtp-secret
              mountPath: /etc/alertmanager/secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
        - name: smtp-secret
          secret:
            secretName: alertmanager-smtp
